language: python

python:
  - "3.8"  # Specify the Python version

install:
  - pip install coverage  # Install the coverage tool

script:
  - coverage run -m unittest discover -s test -p "modified*.py"  # Run tests with coverage
  - coverage report  # Generate and display the coverage report
  - coverage html  # Optional: Generate an HTML coverage report